### ISSUE TITLE
Roadmap for new starters

### ISSUE THREAD

**Issue by cyan33** [PhenixR/HTML-CSS#1]
# Reading Assignment
- [ ] Head First HTML, CSS, XHTML (3-5 days)
- [ ] JavaScript 高级程序设计前4章 (2 days)
- [ ] DOM 编程艺术 (1-2 weeks)
- [ ] w3school (1 week)
- [ ] JavaScript 语言精粹 (1 week)

# Project / Demos
- [x] [Zion-demo](https://thomasyimgit.github.io/Zion-demos/)
- [ ] Vue / React app
